import app from 'flarum/admin/app';

app.initializers.add('ekumanov/claude-reply', () => {
    const reg = app.registry.for('ekumanov-claude-reply');

    const t = (key) => app.translator.trans(`ekumanov-claude-reply.admin.settings.${key}`);

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.enabled',
        type: 'boolean',
        label: t('enabled'),
        help: t('enabled_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.bot_username',
        type: 'text',
        label: t('bot_username'),
        help: t('bot_username_help'),
        placeholder: 'claude_user',
    });

    // Fail-closed allow-lists. Empty means nobody / no tag; that is the point.
    reg.registerSetting({
        setting: 'ekumanov-claude-reply.allowed_user_ids',
        type: 'text',
        label: t('allowed_user_ids'),
        help: t('allowed_user_ids_help'),
        placeholder: '1, 42',
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.allowed_tag_ids',
        type: 'text',
        label: t('allowed_tag_ids'),
        help: t('allowed_tag_ids_help'),
        placeholder: '3, 7',
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.model',
        type: 'text',
        label: t('model'),
        help: t('model_help'),
        placeholder: 'claude-opus-5',
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.effort',
        type: 'select',
        options: {
            low: 'low',
            medium: 'medium',
            high: 'high',
            xhigh: 'xhigh',
            max: 'max',
        },
        default: 'medium',
        label: t('effort'),
        help: t('effort_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.max_tokens',
        type: 'number',
        min: 1024,
        default: 8000,
        label: t('max_tokens'),
        help: t('max_tokens_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.context_token_budget',
        type: 'number',
        min: 1000,
        default: 20000,
        label: t('context_token_budget'),
        help: t('context_token_budget_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.max_context_posts',
        type: 'number',
        min: 1,
        default: 25,
        label: t('max_context_posts'),
        help: t('max_context_posts_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.daily_reply_limit',
        type: 'number',
        min: 0,
        default: 25,
        label: t('daily_reply_limit'),
        help: t('daily_reply_limit_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.persona_prompt',
        type: 'textarea',
        label: t('persona_prompt'),
        help: t('persona_prompt_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.footer',
        type: 'textarea',
        label: t('footer'),
        help: t('footer_help'),
        placeholder: '*This reply was generated by Claude.*',
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.web_search',
        type: 'boolean',
        label: t('web_search'),
        help: t('web_search_help'),
    });

    reg.registerSetting({
        setting: 'ekumanov-claude-reply.web_search_max_uses',
        type: 'number',
        min: 1,
        default: 5,
        label: t('web_search_max_uses'),
        help: t('web_search_max_uses_help'),
    });
});
